### ISSUE TITLE
NanoVgSharp, Aardvark.Rendering.NanoVg, Aardvark.Base.Runtime cannot be found from nuget, please help to provide, thank you.

### ISSUE THREAD

**Issue by Robintjhb** [vrvis/example-scaffolding#2]
Trying to run Stub example failed: these references cannot be found from nuget: NanoVgSharp, Aardvark.Rendering.NanoVg, Aardvark.Base.Runtime, please help to provide, thank you.

**Comment by haraldsteinlechner** [comment]
like any other projects with package dependencies one needs to restore those dependencies in order to properly build the program.
As mentioned in https://github.com/vrvis/aardvark.base/issues/24 in our setups it always works this way: use build.cmd or build.sh to install those packages. (remember that this is nothing special for our projects -- even node.js projects need to be installed by using npm install).

Please note that, although this project works (just tested it) it is kinda outdated. this one is newer: https://github.com/vrvis/template
None of those projects is magical - they simple use a paket.dependencies file where they reference our packages as such:
``
nuget Aardvark.Base.Incremental        ~> 2.0.3
nuget Aardvark.Rendering.Interactive   ~> 2.0.1
``
and by specifying the nuget source: ``source https://vrvis.myget.org/F/aardvark_public/api/v2``

Even if you start from scratch with visual studio you could add this source and add the nuget packages in order to start off.

greetings

**Comment by Robintjhb** [comment]
thank you for patient guidance, the example can run.
